export const skills = {
    heading: "Skills",
    quote: "Build your skills, not your resume",
    techSkills: [
        "JavaScript",
        "NodeJS",
        "ReactJS",
        "React Native",
        "Redux",
        "C++",
        "C#",
        "C",
        "Java",
        "Ajax",
        "HTML",
        "CSS",
        "jQuery",
        "Bootstrap",
        "Material Design",
        "MaterializeCSS",
        "Git",
        "GitHub",
        "MongoDB",
        "Indexeddb",
        "Mysql",
        "service worker",
        "Progressive web application",
        "ASP.net",
        ".Net",
    ],
    industryKnowledge: [
        "Software",
         "Teaching",
        "Creative Writing",
        "Web Content",
        "Frontend",
        "Software",
        "Backend",
        "Design",
        "Web",
        "Android"
    ],
    interpersonalSkills: [
        "Communication",
        "Teaching",
        "Time Management",
        "Leadership",
        "Management"
    ]
};